import { 
  Profile, Client, Project, Milestone, Task, TimeEntry, 
  ProjectFile, Conversation, Message, Proposal, Contract, 
  Invoice, Payment, Notification, ActivityLog 
} from '../../types';

export const SEED_PROFILES: Profile[] = [
  {
    id: 'usr-freelancer-1',
    email: 'sarah.jenkins@freelanceflow.dev',
    full_name: 'Sarah Jenkins',
    role: 'freelancer',
    company_name: 'Studio Jenkins UX/Dev',
    title: 'Senior Product Designer & Full-Stack Engineer',
    bio: 'Specializing in design systems, React, Next.js, and high-conversion web applications.',
    hourly_rate: 2500,
    currency: 'INR',
    phone: '+91 98765 43210',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-06-10T08:00:00Z',
  },
  {
    id: 'usr-client-1',
    email: 'marcus@novalabs.ai',
    full_name: 'Marcus Vance',
    role: 'client',
    company_name: 'Nova Labs',
    title: 'VP of Product',
    phone: '+91 98123 45678',
    currency: 'INR',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-06-15T10:30:00Z',
  },
  {
    id: 'usr-client-2',
    email: 'clara@greenleaf.eco',
    full_name: 'Clara Zhang',
    role: 'client',
    company_name: 'GreenLeaf Studio',
    title: 'Co-Founder & Head of Growth',
    phone: '+91 97234 56789',
    currency: 'INR',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-06-18T14:15:00Z',
  },
  {
    id: 'usr-admin-1',
    email: 'elena.rostova@freelanceflow.dev',
    full_name: 'Elena Rostova',
    role: 'admin',
    company_name: 'FreelanceFlow Core Operations',
    title: 'Platform Lead Administrator',
    currency: 'INR',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-05-01T00:00:00Z',
  }
];

export const SEED_CLIENTS: Client[] = [
  {
    id: 'cli-nova-labs',
    freelancer_id: 'usr-freelancer-1',
    name: 'Nova Labs Inc.',
    company: 'Nova Labs',
    email: 'marcus@novalabs.ai',
    phone: '+91 98123 45678',
    website: 'https://novalabs.ai',
    address: 'Indiranagar 100 Feet Rd, Bengaluru, KA',
    notes: 'High-growth AI startup. Prefers weekly milestone sprint demos on Thursdays.',
    is_archived: false,
    created_at: '2026-06-15T11:00:00Z',
    active_projects_count: 1,
    total_billed: 16250,
  },
  {
    id: 'cli-greenleaf',
    freelancer_id: 'usr-freelancer-1',
    name: 'GreenLeaf Studio',
    company: 'GreenLeaf Studio',
    email: 'clara@greenleaf.eco',
    phone: '+91 97234 56789',
    website: 'https://greenleaf.eco',
    address: 'BKC Bandra East, Mumbai, MH',
    notes: 'Sustainable e-commerce brand. Re-platforming customer experience on Next.js & Shopify API.',
    is_archived: false,
    created_at: '2026-06-18T14:30:00Z',
    active_projects_count: 1,
    total_billed: 12800,
  },
  {
    id: 'cli-apex',
    freelancer_id: 'usr-freelancer-1',
    name: 'Apex Consulting Group',
    company: 'Apex Consulting',
    email: 'david.miller@apexconsulting.com',
    phone: '+91 99345 67890',
    website: 'https://apexconsulting.com',
    address: 'Cyber City, Gurugram, HR',
    notes: 'B2B management consulting boutique. Annual digital brand campaign.',
    is_archived: false,
    created_at: '2026-07-01T09:00:00Z',
    active_projects_count: 1,
    total_billed: 7500,
  }
];

export const SEED_PROJECTS: Project[] = [
  {
    id: 'prj-brand-redesign',
    freelancer_id: 'usr-freelancer-1',
    client_id: 'cli-nova-labs',
    name: 'Brand Website Redesign',
    description: 'Complete overhaul of Nova Labs corporate identity, modern landing pages, interactive product showcase, and developer documentation portal.',
    status: 'active',
    start_date: '2026-08-01',
    deadline: '2026-10-15',
    budget: 18500,
    progress: 68,
    currency: 'INR',
    is_archived: false,
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prj-ecommerce-dashboard',
    freelancer_id: 'usr-freelancer-1',
    client_id: 'cli-greenleaf',
    name: 'E-Commerce Dashboard',
    description: 'Customer analytics, carbon offset tracker, order fulfillment management, and headless checkout optimization.',
    status: 'active',
    start_date: '2026-08-10',
    deadline: '2026-10-30',
    budget: 14000,
    progress: 45,
    currency: 'INR',
    is_archived: false,
    created_at: '2026-08-10T12:00:00Z',
  },
  {
    id: 'prj-social-campaign',
    freelancer_id: 'usr-freelancer-1',
    client_id: 'cli-apex',
    name: 'Social Media Campaign & Assets',
    description: 'Design system for digital ads, LinkedIn leadership carousels, downloadable whitepaper templates, and campaign microsite.',
    status: 'planning',
    start_date: '2026-09-01',
    deadline: '2026-11-15',
    budget: 9500,
    progress: 20,
    currency: 'INR',
    is_archived: false,
    created_at: '2026-08-28T16:00:00Z',
  }
];

export const SEED_MILESTONES: Milestone[] = [
  {
    id: 'mls-1',
    project_id: 'prj-brand-redesign',
    title: 'Phase 1: Discovery & Wireframing',
    description: 'Stakeholder interviews, brand positioning, and low-fidelity architectural wireframes.',
    due_date: '2026-08-18',
    status: 'completed',
    amount: 9250,
    order_index: 1,
    created_at: '2026-08-02T10:00:00Z',
  },
  {
    id: 'mls-2',
    project_id: 'prj-brand-redesign',
    title: 'Phase 2: High-Fidelity UI System',
    description: 'Figma component library, responsive landing pages, and interactive prototypes.',
    due_date: '2026-09-10',
    status: 'completed',
    amount: 4625,
    order_index: 2,
    created_at: '2026-08-02T10:05:00Z',
  },
  {
    id: 'mls-3',
    project_id: 'prj-brand-redesign',
    title: 'Phase 3: Frontend Engineering & CMS Integration',
    description: 'Next.js 15, Tailwind CSS, Supabase backend integration, and SEO optimization.',
    due_date: '2026-10-01',
    status: 'in_progress',
    amount: 2312,
    order_index: 3,
    created_at: '2026-08-02T10:10:00Z',
  },
  {
    id: 'mls-4',
    project_id: 'prj-brand-redesign',
    title: 'Phase 4: QA, User Acceptance & Launch',
    description: 'Cross-browser testing, accessibility audit, DNS handover, and analytics setup.',
    due_date: '2026-10-15',
    status: 'pending',
    amount: 2313,
    order_index: 4,
    created_at: '2026-08-02T10:15:00Z',
  }
];

export const SEED_TASKS: Task[] = [
  {
    id: 'tsk-1',
    project_id: 'prj-brand-redesign',
    milestone_id: 'mls-3',
    assigned_to: 'usr-freelancer-1',
    title: 'Design homepage responsive hero & navigation',
    description: 'Create sticky desktop navbar with animated mobile drawer and high-contrast CTA.',
    status: 'completed',
    priority: 'high',
    due_date: '2026-09-05',
    estimated_hours: 12,
    project_name: 'Brand Website Redesign',
    created_at: '2026-08-20T09:00:00Z',
  },
  {
    id: 'tsk-2',
    project_id: 'prj-brand-redesign',
    milestone_id: 'mls-3',
    assigned_to: 'usr-freelancer-1',
    title: 'Build authentication & protected member area',
    description: 'Implement Supabase auth with role-based dashboard redirects and session recovery.',
    status: 'in_progress',
    priority: 'urgent',
    due_date: '2026-09-22',
    estimated_hours: 16,
    project_name: 'Brand Website Redesign',
    created_at: '2026-08-22T11:00:00Z',
  },
  {
    id: 'tsk-3',
    project_id: 'prj-brand-redesign',
    milestone_id: 'mls-3',
    assigned_to: 'usr-freelancer-1',
    title: 'Prepare content architecture & asset pipeline',
    description: 'Collate customer testimonials, high-res 3D model renders, and copy approvals.',
    status: 'todo',
    priority: 'medium',
    due_date: '2026-09-28',
    estimated_hours: 8,
    project_name: 'Brand Website Redesign',
    created_at: '2026-08-25T14:00:00Z',
  },
  {
    id: 'tsk-4',
    project_id: 'prj-brand-redesign',
    milestone_id: 'mls-4',
    assigned_to: 'usr-client-1',
    title: 'Client review & sign-off on staging environment',
    description: 'Executive review by Marcus Vance and marketing committee before production cutover.',
    status: 'review',
    priority: 'high',
    due_date: '2026-10-05',
    estimated_hours: 4,
    project_name: 'Brand Website Redesign',
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'tsk-5',
    project_id: 'prj-ecommerce-dashboard',
    assigned_to: 'usr-freelancer-1',
    title: 'Build carbon offset calculation widget',
    description: 'Formula to compute real-time grams of CO2 saved per eco-friendly parcel delivery.',
    status: 'in_progress',
    priority: 'medium',
    due_date: '2026-09-25',
    estimated_hours: 10,
    project_name: 'E-Commerce Dashboard',
    created_at: '2026-08-26T15:00:00Z',
  },
  {
    id: 'tsk-6',
    project_id: 'prj-social-campaign',
    assigned_to: 'usr-freelancer-1',
    title: 'Draft LinkedIn carousel templates',
    description: 'Set up modular typographic slide templates with Apex brand guidelines.',
    status: 'todo',
    priority: 'low',
    due_date: '2026-10-10',
    estimated_hours: 6,
    project_name: 'Social Media Campaign & Assets',
    created_at: '2026-09-02T13:00:00Z',
  }
];

export const SEED_TIME_ENTRIES: TimeEntry[] = [
  {
    id: 'tim-1',
    user_id: 'usr-freelancer-1',
    project_id: 'prj-brand-redesign',
    task_id: 'tsk-1',
    description: 'Polished responsive layout and verified 44px mobile touch targets',
    duration_minutes: 240,
    started_at: '2026-09-12T09:00:00Z',
    ended_at: '2026-09-12T13:00:00Z',
    is_billable: true,
    hourly_rate: 2500,
    project_name: 'Brand Website Redesign',
    task_title: 'Design homepage responsive hero & navigation',
    created_at: '2026-09-12T13:00:00Z',
  },
  {
    id: 'tim-2',
    user_id: 'usr-freelancer-1',
    project_id: 'prj-brand-redesign',
    task_id: 'tsk-2',
    description: 'Supabase RLS policies and role verification middleware',
    duration_minutes: 360,
    started_at: '2026-09-14T10:00:00Z',
    ended_at: '2026-09-14T16:00:00Z',
    is_billable: true,
    hourly_rate: 2500,
    project_name: 'Brand Website Redesign',
    task_title: 'Build authentication & protected member area',
    created_at: '2026-09-14T16:00:00Z',
  },
  {
    id: 'tim-3',
    user_id: 'usr-freelancer-1',
    project_id: 'prj-ecommerce-dashboard',
    task_id: 'tsk-5',
    description: 'Carbon emissions mathematical model and interactive chart implementation',
    duration_minutes: 180,
    started_at: '2026-09-15T13:00:00Z',
    ended_at: '2026-09-15T16:00:00Z',
    is_billable: true,
    hourly_rate: 2500,
    project_name: 'E-Commerce Dashboard',
    task_title: 'Build carbon offset calculation widget',
    created_at: '2026-09-15T16:00:00Z',
  }
];

export const SEED_FILES: ProjectFile[] = [
  {
    id: 'fil-1',
    project_id: 'prj-brand-redesign',
    task_id: 'tsk-1',
    uploaded_by: 'usr-freelancer-1',
    file_name: 'NovaLabs-Design-System-v2.pdf',
    file_url: 'https://images.unsplash.com/photo-1581291518655-9523c932edcf?w=600&auto=format&fit=crop&q=80',
    storage_path: 'project-files/prj-brand-redesign/NovaLabs-Design-System-v2.pdf',
    file_type: 'application/pdf',
    file_size: 4820000,
    created_at: '2026-09-08T11:20:00Z',
    uploader_name: 'Sarah Jenkins',
    project_name: 'Brand Website Redesign',
  },
  {
    id: 'fil-2',
    project_id: 'prj-brand-redesign',
    uploaded_by: 'usr-client-1',
    file_name: 'NovaLabs_Brand_Guidelines_2026.zip',
    file_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    storage_path: 'project-files/prj-brand-redesign/NovaLabs_Brand_Guidelines_2026.zip',
    file_type: 'application/zip',
    file_size: 18450000,
    created_at: '2026-08-04T15:45:00Z',
    uploader_name: 'Marcus Vance',
    project_name: 'Brand Website Redesign',
  },
  {
    id: 'fil-3',
    project_id: 'prj-ecommerce-dashboard',
    uploaded_by: 'usr-freelancer-1',
    file_name: 'GreenLeaf_Architecture_Diagram.png',
    file_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
    storage_path: 'project-files/prj-ecommerce-dashboard/GreenLeaf_Architecture_Diagram.png',
    file_type: 'image/png',
    file_size: 1240000,
    created_at: '2026-08-15T16:10:00Z',
    uploader_name: 'Sarah Jenkins',
    project_name: 'E-Commerce Dashboard',
  }
];

export const SEED_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-nova-redesign',
    project_id: 'prj-brand-redesign',
    title: 'Brand Website Redesign — Discussion',
    is_group: true,
    created_at: '2026-08-01T10:30:00Z',
    last_message: 'The new responsive prototype is up on the staging server for your review!',
    last_message_at: '2026-09-16T14:32:00Z',
    project_name: 'Brand Website Redesign',
  },
  {
    id: 'conv-greenleaf',
    project_id: 'prj-ecommerce-dashboard',
    title: 'GreenLeaf — Dashboard Sync',
    is_group: true,
    created_at: '2026-08-10T12:30:00Z',
    last_message: 'Reviewed the carbon metric formula. Looks accurate to standard environmental metrics.',
    last_message_at: '2026-09-15T09:15:00Z',
    project_name: 'E-Commerce Dashboard',
  }
];

export const SEED_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    conversation_id: 'conv-nova-redesign',
    sender_id: 'usr-freelancer-1',
    content: 'Hi Marcus! Welcome to your project workspace on FreelanceFlow. I have initialized the milestone roadmap.',
    created_at: '2026-08-01T10:35:00Z',
    sender: SEED_PROFILES[0],
  },
  {
    id: 'msg-2',
    conversation_id: 'conv-nova-redesign',
    sender_id: 'usr-client-1',
    content: 'Thanks Sarah! Really excited about this redesign. Uploaded the 2026 vector logos and typography guidelines in the Files section.',
    created_at: '2026-08-01T11:05:00Z',
    sender: SEED_PROFILES[1],
  },
  {
    id: 'msg-3',
    conversation_id: 'conv-nova-redesign',
    sender_id: 'usr-freelancer-1',
    content: 'Received! Milestone 1 (Discovery & Wireframing) is complete. The new responsive prototype is up on the staging server for your review!',
    created_at: '2026-09-16T14:32:00Z',
    sender: SEED_PROFILES[0],
  }
];

export const SEED_PROPOSALS: Proposal[] = [
  {
    id: 'prop-1',
    freelancer_id: 'usr-freelancer-1',
    client_id: 'cli-nova-labs',
    project_id: 'prj-brand-redesign',
    title: 'Nova Labs Web Overhaul & Design System Proposal',
    content: 'Comprehensive delivery including Figma token library, Next.js frontend, Supabase database, responsive UI, high-speed performance score >95, and 30 days post-launch support.',
    estimated_amount: 18500,
    currency: 'INR',
    status: 'accepted',
    valid_until: '2026-08-15',
    created_at: '2026-07-20T10:00:00Z',
  },
  {
    id: 'prop-2',
    freelancer_id: 'usr-freelancer-1',
    client_id: 'cli-apex',
    project_id: 'prj-social-campaign',
    title: 'Q3 Executive Digital Campaign & Thought Leadership Suite',
    content: 'Deliverables: 16 custom LinkedIn graphic carousels, 2 interactive whitepaper microsites, and asset management documentation.',
    estimated_amount: 9500,
    currency: 'INR',
    status: 'sent',
    valid_until: '2026-09-30',
    created_at: '2026-08-28T14:00:00Z',
  }
];

export const SEED_CONTRACTS: Contract[] = [
  {
    id: 'cnt-1',
    freelancer_id: 'usr-freelancer-1',
    client_id: 'cli-nova-labs',
    project_id: 'prj-brand-redesign',
    title: 'Master Services Agreement: Nova Labs Redesign',
    terms: '1. Scope of Work: As defined in accepted Proposal #prop-1. 2. Payment Terms: 50% upfront, 25% at Milestone 2, 25% upon final deployment. 3. IP Rights: Client retains 100% ownership upon full payment.',
    total_value: 18500,
    status: 'accepted',
    signed_at: '2026-07-28T16:00:00Z',
    created_at: '2026-07-25T11:00:00Z',
  },
  {
    id: 'cnt-2',
    freelancer_id: 'usr-freelancer-1',
    client_id: 'cli-greenleaf',
    project_id: 'prj-ecommerce-dashboard',
    title: 'Software Development Agreement: GreenLeaf Dashboard',
    terms: 'Fixed price delivery of carbon tracking dashboard with two revision sprints and 60 days warranty.',
    total_value: 14000,
    status: 'accepted',
    signed_at: '2026-08-09T17:00:00Z',
    created_at: '2026-08-08T09:00:00Z',
  }
];

export const SEED_INVOICES: Invoice[] = [
  {
    id: 'inv-2026-001',
    freelancer_id: 'usr-freelancer-1',
    client_id: 'cli-nova-labs',
    project_id: 'prj-brand-redesign',
    invoice_number: 'INV-2026-001',
    issue_date: '2026-08-01',
    due_date: '2026-08-15',
    subtotal: 9250,
    tax_rate: 0,
    tax_amount: 0,
    total_amount: 9250,
    amount_paid: 9250,
    balance_due: 0,
    status: 'paid',
    notes: 'Phase 1 deposit (50% upfront) for Brand Website Redesign.',
    created_at: '2026-08-01T12:00:00Z',
    items: [
      {
        id: 'item-1',
        invoice_id: 'inv-2026-001',
        description: 'Brand Discovery, Stakeholder Analysis, & Wireframing Deposit',
        quantity: 1,
        unit_price: 9250,
        amount: 9250,
        total: 9250,
      }
    ]
  },
  {
    id: 'inv-2026-002',
    freelancer_id: 'usr-freelancer-1',
    client_id: 'cli-nova-labs',
    project_id: 'prj-brand-redesign',
    invoice_number: 'INV-2026-002',
    issue_date: '2026-09-10',
    due_date: '2026-09-24',
    subtotal: 4625,
    tax_rate: 0,
    tax_amount: 0,
    total_amount: 4625,
    amount_paid: 0,
    balance_due: 4625,
    status: 'sent',
    notes: 'Phase 2 Milestone Completion: High-Fidelity UI System approval.',
    created_at: '2026-09-10T15:00:00Z',
    items: [
      {
        id: 'item-2',
        invoice_id: 'inv-2026-002',
        description: 'Figma Design System & High-Fidelity Interactive Prototypes',
        quantity: 1,
        unit_price: 4625,
        amount: 4625,
        total: 4625,
      }
    ]
  },
  {
    id: 'inv-2026-003',
    freelancer_id: 'usr-freelancer-1',
    client_id: 'cli-greenleaf',
    project_id: 'prj-ecommerce-dashboard',
    invoice_number: 'INV-2026-003',
    issue_date: '2026-08-12',
    due_date: '2026-08-26',
    subtotal: 7000,
    tax_rate: 0,
    tax_amount: 0,
    total_amount: 7000,
    amount_paid: 7000,
    balance_due: 0,
    status: 'paid',
    notes: 'Project kickoff deposit (50%) for GreenLeaf Eco-Dashboard.',
    created_at: '2026-08-12T10:00:00Z',
    items: [
      {
        id: 'item-3',
        invoice_id: 'inv-2026-003',
        description: 'Dashboard Sprint 1: Carbon Engine & Shopify sync architecture',
        quantity: 1,
        unit_price: 7000,
        amount: 7000,
        total: 7000,
      }
    ]
  }
];

export const SEED_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    invoice_id: 'inv-2026-001',
    amount: 9250,
    payment_date: '2026-08-05',
    payment_method: 'bank_wire',
    status: 'completed',
    reference: 'WIRE-NVL-8942',
    notes: 'Received via Bank Transfer (NEFT/RTGS).',
    created_at: '2026-08-05T14:30:00Z',
    invoice_number: 'INV-2026-001',
    client_name: 'Nova Labs Inc.',
  },
  {
    id: 'pay-2',
    invoice_id: 'inv-2026-003',
    amount: 7000,
    payment_date: '2026-08-18',
    payment_method: 'ach',
    status: 'completed',
    reference: 'UPI-GLS-1194',
    notes: 'Direct bank transfer cleared.',
    created_at: '2026-08-18T10:00:00Z',
    invoice_number: 'INV-2026-003',
    client_name: 'GreenLeaf Studio',
  }
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    user_id: 'usr-freelancer-1',
    title: 'Payment Received',
    message: 'Nova Labs sent payment of ₹9,250 for INV-2026-001.',
    link: '/invoices',
    type: 'payment',
    is_read: false,
    created_at: '2026-08-05T14:35:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'usr-freelancer-1',
    title: 'Proposal Accepted',
    message: 'Nova Labs accepted proposal "Nova Labs Web Overhaul".',
    link: '/proposals',
    type: 'proposal',
    is_read: true,
    created_at: '2026-07-28T16:05:00Z',
  },
  {
    id: 'notif-3',
    user_id: 'usr-freelancer-1',
    title: 'Milestone Deadline Approaching',
    message: 'Phase 3: Frontend Engineering is due on October 1st.',
    link: '/projects',
    type: 'task',
    is_read: false,
    created_at: '2026-09-16T08:00:00Z',
  }
];

export const SEED_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    user_id: 'usr-freelancer-1',
    project_id: 'prj-brand-redesign',
    action: 'created',
    entity_type: 'task',
    entity_id: 'tsk-2',
    user_name: 'Sarah Jenkins',
    project_name: 'Brand Website Redesign',
    details: { title: 'Build authentication & protected member area' },
    created_at: '2026-09-14T11:00:00Z',
  },
  {
    id: 'act-2',
    user_id: 'usr-client-1',
    project_id: 'prj-brand-redesign',
    action: 'uploaded',
    entity_type: 'file',
    entity_id: 'fil-2',
    user_name: 'Marcus Vance',
    project_name: 'Brand Website Redesign',
    details: { file_name: 'NovaLabs_Brand_Guidelines_2026.zip' },
    created_at: '2026-08-04T15:45:00Z',
  },
  {
    id: 'act-3',
    user_id: 'usr-freelancer-1',
    project_id: 'prj-brand-redesign',
    action: 'sent',
    entity_type: 'invoice',
    entity_id: 'inv-2026-002',
    user_name: 'Sarah Jenkins',
    project_name: 'Brand Website Redesign',
    details: { invoice_number: 'INV-2026-002', amount: 4625 },
    created_at: '2026-09-10T15:00:00Z',
  }
];
